In [1]:
import pandas as pd 
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

In [3]:
df = pd.read_csv('data\processed_data(by_quarter).csv')
df.head()

,Unnamed: 0,duration,goal_usd,blurb_length,name_length,usd_pledged,success,US based,main_category_comics,main_category_crafts,...,main_category_games,main_category_journalism,main_category_music,main_category_photography,main_category_publishing,main_category_technology,main_category_theater,start_Q_Q2,start_Q_Q3,start_Q_Q4
0,0,0.163043,0.000015,0.382353,0.230769,0.000705,1.0,1.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,1,0.315217,0.000030,0.676471,0.269231,0.000455,1.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,2,0.315217,0.000009,0.588235,0.230769,0.000129,1.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
3,3,0.478261,0.000027,0.411765,0.192308,0.000559,1.0,1.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,4,0.641304,0.000232,0.411765,0.115385,0.004696,1.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0

In [4]:
df.drop(['Unnamed: 0', 'usd_pledged'], axis = 1, inplace = True)
df.head()

,duration,goal_usd,blurb_length,name_length,success,US based,main_category_comics,main_category_crafts,main_category_dance,main_category_design,...,main_category_games,main_category_journalism,main_category_music,main_category_photography,main_category_publishing,main_category_technology,main_category_theater,start_Q_Q2,start_Q_Q3,start_Q_Q4
0,0.163043,0.000015,0.382353,0.230769,1.0,1.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,0.315217,0.000030,0.676471,0.269231,1.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,0.315217,0.000009,0.588235,0.230769,1.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
3,0.478261,0.000027,0.411765,0.192308,1.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,0.641304,0.000232,0.411765,0.115385,1.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0

## Develop Logistic Regression Model on data (with Goal USD)

In [5]:
 #1 : split x and y
y = df['success']
x = df.drop('success',axis=1)

#2: split test and train
x_train, x_test, y_train, y_test = train_test_split(x,y,train_size = 0.8, random_state = 42) #shuffle = False that means no random

In [6]:
#3: build the model, fit the train data
log = LogisticRegression()
log.fit(x_train, y_train)

LogisticRegression()

In [15]:
#4: cross_val_score 
accuracy = cross_val_score(log, x_train, y_train, cv = 5)
print ('KFolds cross validation: \n ', accuracy)
print ()
print ('Mean accuracy: \n', accuracy.mean())
print ()
print ('Coefficient of feature: \n')
for index, co in enumerate(log.coef_[0]):
    print (f'Feature {index}: {co:.5f}')

KFolds cross validation:
  [0.6541714  0.6577223  0.65995534 0.66555625 0.65708742]

Mean accuracy:
 0.658898540011138

Coefficient of feature:

Feature 0: -2.33870
Feature 1: -7.30428
Feature 2: -0.69410
Feature 3: 3.07711
Feature 4: 0.12142
Feature 5: 1.15119
Feature 6: -0.56764
Feature 7: 1.15936
Feature 8: 0.20551
Feature 9: -0.11058
Feature 10: 0.20994
Feature 11: -1.09012
Feature 12: 0.16395
Feature 13: -1.04273
Feature 14: 0.45077
Feature 15: -0.52420
Feature 16: 0.55926
Feature 17: -0.85593
Feature 18: 0.31217
Feature 19: -0.02090
Feature 20: -0.12587
Feature 21: -0.00681

In [12]:
#5: Do the prediction
y_pred = log.predict(x_test)
con_matrix = confusion_matrix(y_test, y_pred)
c_report = classification_report(y_test,y_pred)
print ('Confusion matrix: ')
print (con_matrix)
print ()
print ('Classification report: ')
print (c_report)

Confusion matrix:
[[ 7384  7518]
 [ 4093 15151]]

Classification report:
              precision    recall  f1-score   support

         0.0       0.64      0.50      0.56     14902
         1.0       0.67      0.79      0.72     19244

    accuracy                           0.66     34146
   macro avg       0.66      0.64      0.64     34146
weighted avg       0.66      0.66      0.65     34146

## Improve hyperparameters

In [13]:
# Grid SearchCV  to fine tune the model 

from sklearn.model_selection import GridSearchCV
parameters = {'C':np.linspace(0.1,1,10), 'penalty': ['l1', 'l2']} 
search_log = GridSearchCV(log, parameters, n_jobs=-1)
search_log.fit(x_train,y_train)

GridSearchCV(estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ]),
                         'penalty': ['l1', 'l2']})

In [14]:
print(search_log.best_score_)
print(search_log.best_params_)

0.658898540011138
{'C': 1.0, 'penalty': 'l2'}

##  Conclusion: The default value parameters gives the best model.